micronaut.application.name=aluguelcarros

datasources.default.db-type=postgres
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.url=jdbc:postgresql://localhost:5432/aluguel_carros
datasources.default.username=postgres
datasources.default.password=admin

micronaut.router.static-resources.jsonschema.mapping=/schemas/**
micronaut.router.static-resources.jsonschema.paths=classpath\:META-INF/schemas